# Jinja2 Templating - 1
# Task: With help of vars variables in a playbook. 
# Update the msg field in debug task to print - "The name is bond! james bond!" 

# Note: Don't use the name as it is. Use vars variables to print these names.

# ---------------------------

-
  name: Test Jinja2 Templating
  hosts: localhost
  vars:
    first_name: james
    last_name: bond
  tasks:
  - debug:
      msg: 'The name is {{ last_name }}! {{ first_name }} {{ last_name }}!'
