# Jinja2 Templating - 2

# Task: Update the msg field in debug task to print name 
# in title case - "The name is Bond! James Bond!" 

# --------------


-
  name: Test Jinja2 Templating
  hosts: localhost
  vars:
    first_name: james
    last_name: bond
  tasks:
  - debug:
      msg: 'The name is {{ last_name  | title }}! {{ first_name | title }} {{last_name | title}}!'
